### ISSUE TITLE
As a Just Eat customer, I can install a web extension to display hygiene ratings, so that I can make more informed outlet choices.

### ISSUE THREAD

**Issue by alexbfree** [alexbfree/just-eat-booster#6]
# Summary

Ability for a Just Eat customer to install a web extension. The web extension will contact our Hygiene Rating Service and give the user the ability to see hygiene rating next to each outlet while browsing the site.

# Dependencies

Cannot be done until #2 is completed.

# Tasks

- [ ] new shell chrome extension
- [ ] develop graphics for showing rating (mostly already done)
- [ ] modify the outlets page so that after load, it collects the list of ratings for the current postcode (or a list of outlets, TBC)
- [ ] 

[..]
